# Generated by Django 3.0.8 on 2021-07-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0002_auto_20210718_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
