# Generated by Django 3.0.8 on 2021-07-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0004_auto_20210720_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=models.SlugField(default='other', max_length=30),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(default='Other', max_length=30),
        ),
    ]
