# Generated by Django 3.0.8 on 2021-07-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0005_auto_20210721_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(default='Untitled', max_length=40),
        ),
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(default='other', max_length=40),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(default='Other', max_length=40),
        ),
    ]
