# Generated by Django 3.0.8 on 2021-07-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0006_auto_20210721_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='slug',
            field=models.SlugField(default='other', max_length=40),
        ),
    ]
