# Generated by Django 3.0.8 on 2021-07-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0007_quiz_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='slug',
            field=models.SlugField(max_length=40, null=True),
        ),
    ]
