# Generated by Django 3.0.8 on 2021-07-22 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0009_answer_option_participantanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option10',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option3',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option4',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option5',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option6',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option7',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option8',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option9',
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='quizApp.Question'),
        ),
    ]
