# Generated by Django 3.0.8 on 2021-07-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0011_auto_20210722_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='time_finished',
            field=models.DateTimeField(default=''),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='deadline',
            field=models.DateTimeField(default=''),
        ),
    ]
