# Generated by Django 3.0.8 on 2021-07-22 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0013_auto_20210722_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='time_finished',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 22, 20, 47, 28, 920508)),
        ),
    ]
