# Generated by Django 3.0.8 on 2021-07-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0014_auto_20210722_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='time_finished',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='deadline',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
