# Generated by Django 3.0.8 on 2021-07-22 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0015_auto_20210722_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='deadline',
        ),
    ]
