# Generated by Django 3.0.8 on 2021-07-23 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0017_auto_20210723_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantAnswer_connect_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quizApp.ParticipantAnswer')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connect_to_participant_answer', to='quizApp.Quiz')),
            ],
        ),
    ]
