# Generated by Django 3.0.8 on 2021-07-23 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0019_auto_20210723_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantanswer_question_quiz_connections',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ParticipantAnswer_Question_Quiz_connections', to='quizApp.Question'),
        ),
    ]
