# Generated by Django 3.0.8 on 2021-07-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0020_auto_20210723_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='ParticipantAnswer_Question_Quiz_connections',
        ),
    ]
