# Generated by Django 3.0.8 on 2021-07-25 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0021_auto_20210723_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('C', 'College Students'), ('G', 'Graduate'), ('W', 'Working')], default=('C', 'College Students'), max_length=50),
        ),
    ]
