# Generated by Django 3.0.8 on 2021-07-25 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0022_user_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='average_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('C', 'College Students'), ('G', 'Graduate'), ('W', 'Working')], default='College Students', max_length=50),
        ),
    ]
