# Generated by Django 3.0.8 on 2021-07-25 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0023_auto_20210725_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='average_score',
        ),
    ]
