# Generated by Django 3.0.8 on 2021-07-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0025_user_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='media/profile/user.png', upload_to='media/profile/'),
        ),
    ]
