# Generated by Django 3.0.8 on 2021-07-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0026_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='participant',
            name='time_start',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('O', 'Other'), ('C', 'College Students'), ('G', 'Graduate'), ('W', 'Working')], default='Other', max_length=50),
        ),
    ]
